backend:
  name: git-gateway
  repo: BlendiSpahiu/remix-netlify
  branch: main
  
site_url: https://stirring-arithmetic-63c4dd.netlify.app/

publish_mode: editorial_workflow
media_folder: images
public_folder: images

collections:
  - name: post
    label: Post
    folder: app/routes/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
