backend:
  name: git-gateway
  repo: BlendiSpahiu/remix-netlify
  branch: main
  


publish_mode: editorial_workflow
media_folder: images
public_folder: images

collections:
  - name: post
    label: Post
    folder: posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
